/*
 * Decompiled with CFR 0.150.
 */
package dev.nuker.pyro;

import dev.nuker.pyro.AutoCrystal;
import dev.nuker.pyro.IceSpeed;
import dev.nuker.pyro.Radar;
import dev.nuker.pyro.aura;
import dev.nuker.pyro.criticals;
import dev.nuker.pyro.f68;
import dev.nuker.pyro.f69;
import dev.nuker.pyro.f6A;
import dev.nuker.pyro.f6C;
import dev.nuker.pyro.f6I;
import dev.nuker.pyro.f6J;
import dev.nuker.pyro.f6L;
import dev.nuker.pyro.f6O;
import dev.nuker.pyro.f6R;
import dev.nuker.pyro.f6U;
import dev.nuker.pyro.f6V;
import dev.nuker.pyro.f6W;
import dev.nuker.pyro.f6Y;
import dev.nuker.pyro.f6j;
import dev.nuker.pyro.f6m;
import dev.nuker.pyro.f6u;
import dev.nuker.pyro.f6v;
import dev.nuker.pyro.f6w;
import dev.nuker.pyro.f6y;
import dev.nuker.pyro.f6z;
import dev.nuker.pyro.f70;
import dev.nuker.pyro.f71;
import dev.nuker.pyro.f73;
import dev.nuker.pyro.f74;
import dev.nuker.pyro.f76;
import dev.nuker.pyro.f77;
import dev.nuker.pyro.f78;
import dev.nuker.pyro.f7G;
import dev.nuker.pyro.f7P;
import dev.nuker.pyro.f7Q;
import dev.nuker.pyro.f7R;
import dev.nuker.pyro.f7S;
import dev.nuker.pyro.f7T;
import dev.nuker.pyro.f7V;
import dev.nuker.pyro.f7W;
import dev.nuker.pyro.f7X;
import dev.nuker.pyro.f7Y;
import dev.nuker.pyro.f7b;
import dev.nuker.pyro.f7d;
import dev.nuker.pyro.f7e;
import dev.nuker.pyro.f7p;
import dev.nuker.pyro.f7r;
import dev.nuker.pyro.f7s;
import dev.nuker.pyro.f7t;
import dev.nuker.pyro.f7u;
import dev.nuker.pyro.f7v;
import dev.nuker.pyro.f7y;
import dev.nuker.pyro.f81;
import dev.nuker.pyro.f83;
import dev.nuker.pyro.f84;
import dev.nuker.pyro.f85;
import dev.nuker.pyro.f88;
import dev.nuker.pyro.f89;
import dev.nuker.pyro.f8A;
import dev.nuker.pyro.f8D;
import dev.nuker.pyro.f8E;
import dev.nuker.pyro.f8F;
import dev.nuker.pyro.f8J;
import dev.nuker.pyro.f8K;
import dev.nuker.pyro.f8c;
import dev.nuker.pyro.f8d;
import dev.nuker.pyro.f8g;
import dev.nuker.pyro.f8i;
import dev.nuker.pyro.f8j;
import dev.nuker.pyro.f8k;
import dev.nuker.pyro.f8l;
import dev.nuker.pyro.f8p;
import dev.nuker.pyro.f8q;
import dev.nuker.pyro.f8s;
import dev.nuker.pyro.f8t;
import dev.nuker.pyro.f8u;
import dev.nuker.pyro.f8y;
import dev.nuker.pyro.f8z;
import dev.nuker.pyro.f99;
import dev.nuker.pyro.f9A;
import dev.nuker.pyro.f9C;
import dev.nuker.pyro.f9D;
import dev.nuker.pyro.f9E;
import dev.nuker.pyro.f9F;
import dev.nuker.pyro.f9G;
import dev.nuker.pyro.f9H;
import dev.nuker.pyro.f9J;
import dev.nuker.pyro.f9T;
import dev.nuker.pyro.f9V;
import dev.nuker.pyro.f9Y;
import dev.nuker.pyro.f9Z;
import dev.nuker.pyro.f9a;
import dev.nuker.pyro.f9e;
import dev.nuker.pyro.f9h;
import dev.nuker.pyro.f9i;
import dev.nuker.pyro.f9j;
import dev.nuker.pyro.f9m;
import dev.nuker.pyro.f9p;
import dev.nuker.pyro.f9q;
import dev.nuker.pyro.f9u;
import dev.nuker.pyro.fa1;
import dev.nuker.pyro.faI;
import dev.nuker.pyro.faJ;
import dev.nuker.pyro.faK;
import dev.nuker.pyro.faN;
import dev.nuker.pyro.faO;
import dev.nuker.pyro.faP;
import dev.nuker.pyro.faQ;
import dev.nuker.pyro.faS;
import dev.nuker.pyro.fac;
import dev.nuker.pyro.fb0;
import dev.nuker.pyro.fb4;
import dev.nuker.pyro.fbB;
import dev.nuker.pyro.fbC;
import dev.nuker.pyro.fbD;
import dev.nuker.pyro.fbE;
import dev.nuker.pyro.fbF;
import dev.nuker.pyro.fbJ;
import dev.nuker.pyro.fbN;
import dev.nuker.pyro.fbO;
import dev.nuker.pyro.fbT;
import dev.nuker.pyro.fbX;
import dev.nuker.pyro.fbZ;
import dev.nuker.pyro.fbc;
import dev.nuker.pyro.fbd;
import dev.nuker.pyro.fbe;
import dev.nuker.pyro.fbh;
import dev.nuker.pyro.fbl;
import dev.nuker.pyro.fbm;
import dev.nuker.pyro.fbn;
import dev.nuker.pyro.fbo;
import dev.nuker.pyro.fbr;
import dev.nuker.pyro.fbs;
import dev.nuker.pyro.fbu;
import dev.nuker.pyro.fby;
import dev.nuker.pyro.fd0;
import dev.nuker.pyro.fd4;
import dev.nuker.pyro.fd6;
import dev.nuker.pyro.fd7;
import dev.nuker.pyro.fd9;
import dev.nuker.pyro.fdF;
import dev.nuker.pyro.fdH;
import dev.nuker.pyro.fda;
import dev.nuker.pyro.fdh;
import dev.nuker.pyro.fdk;
import dev.nuker.pyro.fdm;
import dev.nuker.pyro.keypearl;

public class PyroStatic {
    public static fa1 Field6403 = new fa1();
    public static f9h Field6404 = new f9h();
    public static fac Field6405 = new fac();
    public static f9Y Field6406 = new f9Y();
    public static f6j Field6407 = new f6j();
    public static f70 Field6408 = new f70();
    public static fdk Field6409 = new fdk();
    public static f7V Field6410 = new f7V();
    public static f8u Field6411 = new f8u();
    public static fdH Field6412 = new fdH();
    public static f7W Field6413 = new f7W();
    public static f7T Field6414 = new f7T();
    public static f83 Field6415 = new f83();
    public static AutoCrystal Field6416 = new AutoCrystal();
    public static fb4 Field6417 = new fb4();
    public static fbJ Field6418 = new fbJ();
    public static f88 Field6419 = new f88();
    public static fbd Field6420 = new fbd();
    public static f8j Field6421 = new f8j();
    public static f6L Field6422 = new f6L();
    public static f6R Field6423 = new f6R();
    public static fbT Field6424 = new fbT();
    public static f99 Field6425 = new f99();
    public static f8E Field6426 = new f8E();
    public static faN Field6427 = new faN();
    public static f6w Field6428 = new f6w();
    public static f9V Field6429 = new f9V();
    public static f9T Field6430 = new f9T();
    public static f73 Field6431 = new f73();
    public static f9E Field6432 = new f9E();
    public static fbr Field6433 = new fbr();
    public static fbc Field6434 = new fbc();
    public static criticals Field6435 = new criticals();
    public static f9u Field6436 = new f9u();
    public static f9C Field6437 = new f9C();
    public static IceSpeed Field6438 = new IceSpeed();
    public static fd7 Field6439 = new fd7();
    public static fd9 Field6440 = new fd9();
    public static fbZ Field6441 = new fbZ();
    public static f9D Field6442 = new f9D();
    public static fbu Field6443 = new fbu();
    public static f6y Field6444 = new f6y();
    public static aura Field6445 = new aura();
    public static f71 Field6446 = new f71();
    public static f9p Field6447 = new f9p();
    public static f74 Field6448 = new f74();
    public static f7p Field6449 = new f7p();
    public static f7s Field6450 = new f7s();
    public static f78 Field6451 = new f78();
    public static f7b Field6452 = new f7b();
    public static fbl Field6453 = new fbl();
    public static f8J Field6454 = new f8J();
    public static f9A Field6455 = new f9A();
    public static f9i Field6456 = new f9i();
    public static f9j Field6457 = new f9j();
    public static fda Field6458 = new fda();
    public static f68 Field6459 = new f68();
    public static fd4 Field6460 = new fd4();
    public static f9a Field6461 = new f9a();
    public static f9G Field6462 = new f9G();
    public static f6Y Field6463 = new f6Y();
    public static faS Field6464 = new faS();
    public static faO Field6465 = new faO();
    public static fdm Field6466 = new fdm();
    public static faJ Field6467 = new faJ();
    public static fbC Field6468 = new fbC();
    public static f7S Field6469 = new f7S();
    public static fd0 Field6470 = new fd0();
    public static fbO Field6471 = new fbO();
    public static f7e Field6472 = new f7e();
    public static f9F Field6473 = new f9F();
    public static f8K Field6474 = new f8K();
    public static f9m Field6475 = new f9m();
    public static fbo Field6476 = new fbo();
    public static fbs Field6477 = new fbs();
    public static fbE Field6478 = new fbE();
    public static f7t Field6479 = new f7t();
    public static f76 Field6480 = new f76();
    public static f7u Field6481 = new f7u();
    public static Radar Field6482 = new Radar();
    public static f6v Field6483 = new f6v();
    public static f7d Field6484 = new f7d();
    public static f7y Field6485 = new f7y();
    public static f8q Field6486 = new f8q();
    public static f84 Field6487 = new f84();
    public static f7r Field6488 = new f7r();
    public static fby Field6489 = new fby();
    public static f6U Field6490 = new f6U();
    public static f6u Field6491 = new f6u();
    public static fbF Field6492 = new fbF();
    public static f9H Field6493 = new f9H();
    public static f6C Field6494 = new f6C();
    public static faP Field6495 = new faP();
    public static f8z Field6496 = new f8z();
    public static f89 Field6497 = new f89();
    public static f7Y Field6498 = new f7Y();
    public static f7X Field6499 = new f7X();
    public static fbh Field6500 = new fbh();
    public static f6J Field6501 = new f6J();
    public static f6V Field6502 = new f6V();
    public static f8p Field6503 = new f8p();
    public static fdh Field6504 = new fdh();
    public static f85 Field6505 = new f85();
    public static f6W Field6506 = new f6W();
    public static fb0 Field6507 = new fb0();
    public static f6m Field6508 = new f6m();
    public static f8k Field6509 = new f8k();
    public static f6O Field6510 = new f6O();
    public static f8F Field6511 = new f8F();
    public static faI Field6512 = new faI();
    public static faK Field6513 = new faK();
    public static keypearl Field6514 = new keypearl();
    public static fbN Field6515 = new fbN();
    public static f9q Field6516 = new f9q();
    public static f6A Field6517 = new f6A();
    public static f9e Field6518 = new f9e();
    public static f8t Field6519 = new f8t();
    public static fbB Field6520 = new fbB();
    public static fbD Field6521 = new fbD();
    public static f8l Field6522 = new f8l();
    public static faQ Field6523 = new faQ();
    public static f6z Field6524 = new f6z();
    public static fbX Field6525 = new fbX();
    public static f7R Field6526 = new f7R();
    public static f81 Field6527 = new f81();
    public static fbm Field6528 = new fbm();
    public static f8D Field6529 = new f8D();
    public static f9Z Field6530 = new f9Z();
    public static f8g Field6531 = new f8g();
    public static f9J Field6532 = new f9J();
    public static f77 Field6533 = new f77();
    public static f6I Field6534 = new f6I();
    public static f69 Field6535 = new f69();
    public static f8A Field6536 = new f8A();
    public static fbe Field6537 = new fbe();
    public static fd6 Field6538 = new fd6();
    public static f8s Field6539 = new f8s();
    public static f8d Field6540 = new f8d();
    public static f7G Field6541 = new f7G();
    public static f8y Field6542 = new f8y();
    public static f8c Field6543 = new f8c();
    public static fdF Field6544 = new fdF();
    public static f8i Field6545 = new f8i();
    public static fbn Field6546 = new fbn();
    public static f7v Field6547 = new f7v();
    public static f7P Field6548 = new f7P();
    public static f7Q Field6549 = new f7Q();
}

